language: java
install: true

jdk:
  - openjdk11

env:
  global:
    - GPG_FILE_NAME="crypto.types.gpg"
    - ENCRYPTED_GPG_FILE_NAME="crypto.types.gpg.enc"
    - PUBLISH_SNAPSHOT_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots/"
    - PUBLISH_RELEASE_REPO_URL="https://oss.sonatype.org/service/local/staging/deploy/maven2/"
    # PUBLISH_REPO_USERNAME
    - secure: nP90a2uf4OE2KM3xdMU8XYbEv/j+XVHfbyWHtiP0Q8CylCO/MY68GojjHva9OdLKWOK4SIj0RN/Li+BzIXX55n4esj4rZtG70yexWBrTlkelrXpf2H/7k+M1/cj0domhrSpCrZaHevZPFmumV8nZetzLaz/hPAC4HgKGUMI3f5hPop1APdzsa7y7paQW+djo9mNtcdWTWbJOZz+HSo45byGDbokZIlPR7s1Jb0aHyxWshNSJTB/XCqvZJB0PxvHkORGRShFlz7KeFFKnjoYQ3O5xhecQUxiGF5U4MbK8z7fHH2MZj2hc/lIOGcBoW4rQbzeTLjU+RrFupmlIp8rp097tRYwOdp4wPyKuHvDxVqIGHlbE34RDcLbdx09IqmPm41cyjsywwL73FbLvkW2MHMdcvJe1bUvwLS4B6PLcVN5aXn1NxvnusUDRKTeRPV63eomZgLq1pUqQ8Lt8p6V6LT/3fRS286PbwzuPAeW8+6ZDrFkqcuvYuxFevsCHTRGQGwocUSQm3lFrL/1snqdCGUcLM4qI6znNx3FstSvqJT22zwGANdkGDVdFsM/HtB+N8mR0VpnXq6znAqRJYpajAs/Q5uaAsgTT2xOMK63/i2hDCaC9wdB+mIjTEL9SECavUMOfwwzD3KpNNHdQ/Mu6qzwW+/BPbMDUCLyQzsayWgA=
    # PUBLISH_REPO_PASSWORD
    - secure: fm9uUOVYnl1rAtUuAN1yX2AAmgdd8kufee7bYDDcq9zQdEKPliO711+zRWFGfCC/IwqsyGDHRrB1XTagKKSHkImmoI5+y4EaOWa+IJ6eGjT5kTM4SlQYznf6BqtiTAeRzYoFsqJCDGXTzhIkvvJ0G+gP9xEUQBKQQLmx1ajw9pBJ8rppad60k8ZcitK5HjLcXLRp/EqMIwjLLVm1KGZJqQXEtX39hemzlZA+k+xwiCb5JUKN09X1Yu9PbD42je3vuWOQ3pvJIVC7YBuocX8mKvMezb+cidMpmG8DwmsqrSJyus4IPaUQXLAWe1TNGmyr0qwda4SsOu4hbP9RT/1YHqQPWYFKueZq7bnnWnTYlxif7k7WvfrE0cyOBtp3eDnZyckcFpGG3PHoDsSxKualOHVQQz5T5H424ZmA9JNhzl5yPtjf5PhfvQNccZv0T8voV6b12stgjeysBTS6TN7G2MDQf2jZW7G+JVFCKV6Xfl8bEV0M5HSedTKNFVziIPhBA8UmGCuWkvhVoZzLhnloXcLL53eqyJuIQ6gs0ZfkfIN7nNUnxe1Nz+wQlLhm5TqF9lEoY88XDfs4pXlIQu9n9b/fXenx01JubgKKVeGuIBJhe5f/tP8mc+Dd9RYMMF74fch7n4YT7KQymTKBTq+/b33IaLZwngvVXQEsZjp1nKs=
    # GPG_KEY_ID
    - secure: Yj6UYdrhoLKAw9I8xHNx3Q4ISKwe8lBOnLJmBf0dQCyN/zBPVdjEjSMy5R7mf+1Aje3y0CE6zmvC/HZ+N7zTaLodJiXGXc/aL5lpA/rnMSbbKexjgARITcW1KBefOr2j+M4igwICH32BCRNdYYZp+R7zz7WAqCKYe5kiQODBL3r9pC3QQU6Pmf7UOES7pTWzmw3dluDdHS2yKxwz3rsfFetLdzDDZuSRrYknOrgVttBKjkMqjvY7Bl9QXu+h9o56LyXQuowRlaZRwl2iv4JdwNcWnFHZJ+dq4l7qQnRunJresNog9kkr2fIvFV1Rz63vSCev6+AylpHI6eIvZYcC8IffRhSFOceMyUdzTnas1IiBn9l8sLQlqBcdDmN+45gMryMWQWGvorqYNoc7Xw95CSo5nZRW+kkPAMaTkTEpNmQSWKzK06o0MKsThq90GO/A71gQ/9cL+TCgBJtETJQY5mlAL/xz0l5VlyD6WZnnaDQ37ubbqe+040s42xMDSwGoWcgiYWJH5rfhPG4CEaovCcILKUhf/nk9RgStNv93H941FAtUblGcgpP5C66nWv3w5HlPjhSALro1SDRkjKBL1ZqkcJc++7qc41BjHf8dY3PSc0IevSs48PokuCy4s2zZzEpc+sSu6EWk2/8sTnSMG9d548Gf/65iGvO8jJ99o+A=
    # GPG_PASSPHRASE
    - secure: Vil1HoI2pTyBJ+lRveUyFN3mibaMD3UPmvfS30dcpIWzZtwY/WjyAAPr26Wdd15XrIzDcbtzuY98DvkazgBEkb2EwKyTusgLgUtbb0YVzuM651C+pNA0u8j87Mq47TqbLS3tRYtwuXtftslSdz1xgeZ+un5zCP40i6Oy75Ct7y7zIpJ6Bh22p8D7r8nxFcBahXJ69D7UIe8chE0cJnFE8fj/+8fdingekUvK9a5EB10RSYHL48cetE0aboMQLqyLLIOXXDRgzTlE54zIiyxVQtZ1SznVUfIcQbbQoigkNXLf5E9YCdrKjnuXL1MiTk9qH9mv0BdClCGssXvzaku2K3SQsta5rv1UCPIAKO088xwv0g7l84vCnVnWrGlzwRd1+05/NbjMlUgxOG6BKt42/xXyVII3IKyIPDtvpYkimb4QjFZos+sAt4ySm0m7Ufr9cDAwqoAC62aFvOKlqzgLSydrmhx/P0YQHPVeLDgqSZNDfgw3YeTgxqCQcTb8z/qIxHW6zAQHSHa0+Tj3HXHxVCiyJiBGCGTrH83pqxs2YHJYafcFo6gKykFpRYlmSvHZaUDNmzNyvc5k6NBi6VZFK6uiwD/p2s9WCdxj3kCvl0ouAW3ni4YIWfSVlQu5XpZrhZnCP3CZkkcMJntLVgPCfn4fTyAyWjEt+Ys89wiIDBo=

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

before_script:
  - chmod -R ug+x .travis
  - psql -c 'create database encrypt;' -U postgres
  - psql -c 'create role encrypt LOGIN SUPERUSER;' -U postgres

services:
  - postgresql

jobs:
  include:
    - stage: test
      name: Build
      script: ".travis/build.sh"
    - stage: deploy
      name: Deploy Snapshot
      jdk: openjdk11
      if: |
        branch = master AND \
        type = push
      script: ".travis/deploy.sh"
    - stage: deploy
      name: Deploy Release
      jdk: openjdk11
      if: tag IS present AND tag =~ ^(\d)+\.(\d)+(\.(\d)+)*(-[\w]+)*$
      script: ".travis/deploy.sh"
      deploy:
        provider: releases
        api_key:
          secure: mwmEd4XmnfmV9EUFzTyHll4RSISIO9xuhSk9kla5QBuV8D8YIExqwqMVEx5boEO9uVRxWuF2Nvc3XWUznoswUtQtmmEpgDdXL9gCnGn3hsZ2bhNZaMYUmQk5v9RabhNeZtZiTRT3zRnwt+XGNADOG+axeZubY95J98hWA0ZCxtMXGxNOZMTDKLjFQmHKUjyBPrxWOr1i8VUjXQgEqOIs4aVdSNpKR9xrDqJQYn0Z5IwodOBuGhqZb/v9khfvc+cZMuLU+mrTEITZPMvlbsHKPBBGJURu72jX9WPdVi0S8eH30R0JEE+DcCducvSY+OHqIsk1eeE7ct1mqSVkdz3Fw44FT9HeYoyKdjSPBtcYH3g2HG5zskpSL2JBOj3XDOB1/yu8x/e+BI74Hf8MKD6TxYqMRDNAWHVa8fjiErl4jIxImttoZ33ENtWpPp94oo1NmmGV4BMz5GImglMI6vImFJalY2H3KLLQDMSosUpFtFnmC4qCRHbNRxFbUCSFo7NJ81qj54umGb4CoUEqi/+/I3WxRQReH7k8GyV1IRdPVCV4WlWHuVI1LzMwirfA5EeJ+i5JKlSM5Orut5hWyH9kc2JS/Lee4n+2iz8LYdRqs1gn9gV7EDEVCchxVgRPiFu0wpTHSoktnmdB51tdopfTIbYaWK4POurbWTcFTyMmOuc=
        file_glob: true
        file: "$TRAVIS_BUILD_DIR/build/libs/*"
        body: Release of $TRAVIS_TAG
        skip_cleanup: true
        draft: true
        on:
          repo: ekino/hibernate-crypto-types
          tags: true

addons:
  postgresql: '11.2'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
