version: '3'

services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_DB: 'encrypt'
      POSTGRES_USER: 'encrypt'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
